import { Receipt, formatNaira } from "@/lib/receipt";

type ReceiptPreviewProps = {
  receipt: Receipt;
};

export function ReceiptPreview({ receipt }: ReceiptPreviewProps) {
  const statusStyles = {
    paid: "bg-green-100 text-green-700 border-green-200",
    "part-paid": "bg-amber-100 text-amber-700 border-amber-200",
    unpaid: "bg-red-100 text-red-700 border-red-200",
  };

  return (
    <div
      id="receipt-preview"
      className="w-full max-w-md rounded-3xl border border-zinc-200 bg-white p-6 shadow-sm"
    >
      <div className="border-b border-dashed border-zinc-300 pb-5">
        <div className="flex items-start justify-between gap-4">
          <div>
            <h2 className="text-2xl font-black tracking-tight text-zinc-950">
              {receipt.businessName}
            </h2>

            <p className="mt-1 text-sm text-zinc-500">Official Receipt</p>

            {(receipt.businessPhone || receipt.businessAddress) && (
              <div className="mt-2 space-y-1 text-xs font-medium text-zinc-500">
                {receipt.businessPhone && <p>{receipt.businessPhone}</p>}
                {receipt.businessAddress && <p>{receipt.businessAddress}</p>}
              </div>
              )}
          </div>

          <span
            className={`rounded-full border px-3 py-1 text-xs font-bold uppercase tracking-wide ${
              statusStyles[receipt.paymentStatus]
            }`}
          >
            {receipt.paymentStatus}
          </span>
        </div>

        <div className="mt-5 grid grid-cols-2 gap-3 text-sm">
          <div>
            <p className="text-zinc-500">Receipt No.</p>
            <p className="font-semibold text-zinc-900">
              {receipt.receiptNumber}
            </p>
          </div>

          <div className="text-right">
            <p className="text-zinc-500">Date</p>
            <p className="font-semibold text-zinc-900">
              {new Date(receipt.issuedAt).toLocaleDateString("en-NG")}
            </p>
          </div>
        </div>
      </div>

      <div className="border-b border-dashed border-zinc-300 py-5">
        <p className="text-sm text-zinc-500">Customer</p>
        <p className="mt-1 text-lg font-bold text-zinc-950">
          {receipt.customerName}
        </p>
      </div>

      <div className="border-b border-dashed border-zinc-300 py-5">
        <div className="mb-3 flex items-center justify-between text-sm font-semibold text-zinc-500">
          <span>Item</span>
          <span>Amount</span>
        </div>

        {receipt.items.map((item, index) => (
          <div key={index} className="flex items-start justify-between gap-4">
            <p className="text-sm font-medium text-zinc-900">
              {item.description}
            </p>
            <p className="text-sm font-semibold text-zinc-900">
              {item.total ? formatNaira(item.total) : "—"}
            </p>
          </div>
        ))}
      </div>

      <div className="space-y-3 py-5">
        <div className="flex justify-between text-sm">
          <span className="text-zinc-500">Total</span>
          <span className="font-bold text-zinc-950">
            {formatNaira(receipt.totalAmount)}
          </span>
        </div>

        <div className="flex justify-between text-sm">
          <span className="text-zinc-500">Paid</span>
          <span className="font-bold text-zinc-950">
            {formatNaira(receipt.amountPaid)}
          </span>
        </div>

        <div className="flex items-center justify-between rounded-2xl bg-zinc-950 px-4 py-4 text-white">
          <span className="text-sm text-zinc-300">Balance</span>
          <span className="text-xl font-black">
            {formatNaira(receipt.balance)}
          </span>
        </div>
      </div>

      <div className="border-t border-dashed border-zinc-300 pt-5 text-center">
        <p className="text-sm font-medium text-zinc-700">
          Thank you for your business.
        </p>
        <p className="mt-1 text-xs text-zinc-400">
          Generated by VoiceReceipt
        </p>
      </div>
    </div>
  );
}
